CREATE DATABASE IF NOT EXISTS  Pizzeria;
USE Pizzeria;

DROP TABLE IF EXISTS PRODUCTOS_ADICIONALES;
DROP TABLE IF EXISTS PRODUCTOS_INGREDIENTES;
DROP TABLE IF EXISTS TIPOPRODUCTOS_PRODUCTOS;
DROP TABLE IF EXISTS ADICIONALES;
DROP TABLE IF EXISTS INGREDIENTES;
DROP TABLE IF EXISTS PRODUCTOS;
DROP TABLE IF EXISTS TIPO_PRODUCTO;
DROP TABLE IF EXISTS CATEGORIAS;

CREATE TABLE CATEGORIAS (
	IDCategorias int AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE TIPO_PRODUCTO(
	IDTipoProducto int AUTO_INCREMENT PRIMARY KEY,
	nombre  varchar(50)
);

CREATE TABLE PRODUCTOS(
	IDProductos int AUTO_INCREMENT PRIMARY KEY,
	IDCategorias int,
	nombre varchar(60),
	descripción varchar(100),
	precio int(6),
    CONSTRAINT FKCategorias FOREIGN KEY(IDCategorias) REFERENCES CATEGORIAS(IDCategorias) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE INGREDIENTES(
	IDIngredientes int AUTO_INCREMENT PRIMARY KEY,
	nombre varchar(60),
	stock_disponible int,
	fecha_vencimiento date
);

CREATE TABLE ADICIONALES(
	IDAdicionales int AUTO_INCREMENT PRIMARY KEY,
	nombre varchar(60),
	descripción varchar(100),
	cantidades bigint,
    precio_adicional int(6)
);

CREATE TABLE TIPOPRODUCTOS_PRODUCTOS(
	IDTipPro int AUTO_INCREMENT PRIMARY KEY,
    IDTipoProducto int,
	IDProductos int,
    CONSTRAINT FKTipoProducto FOREIGN KEY(IDTipoProducto) REFERENCES TIPO_PRODUCTO(IDTipoProducto) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FKProductosTipPro FOREIGN KEY(IDProductos) REFERENCES PRODUCTOS(IDProductos) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE PRODUCTOS_INGREDIENTES(
	IDProIngre int AUTO_INCREMENT PRIMARY KEY,
	IDProductos int,
	IDIngredientes int,
    CONSTRAINT FKProductosIngred FOREIGN KEY(IDProductos) REFERENCES PRODUCTOS(IDProductos) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FKIngredientes FOREIGN KEY(IDIngredientes) REFERENCES INGREDIENTES(IDIngredientes) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE PRODUCTOS_ADICIONALES(
	IDProAdc int AUTO_INCREMENT PRIMARY KEY,
	IDProductos int,
	IDAdicionales int,
    CONSTRAINT FKProductosAdicionales FOREIGN KEY(IDProductos) REFERENCES PRODUCTOS(IDProductos) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT FKAdicionales FOREIGN KEY(IDAdicionales) REFERENCES ADICIONALES(IDAdicionales) ON DELETE NO ACTION ON UPDATE CASCADE
);